#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.18

pipelines:
  branches:
    adidev:
      - step:
          name: TestBuild
          script:
            - echo "This step will run on a self hosted runner with 128 GB of memory.";
