#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.18

pipelines:
  default:
    - parallel:
      - step:
          name: Test and Build
          script:
            - mkdir test-reports
            - go install github.com/jstemmer/go-junit-report/v2@latest
            - go test tests/* -v 2>&1 | go-junit-report > test-reports/report.xml
            - go build server/main.go
          artifacts:
            - report.xml
            # Build compiles the packages
      - step:
          name: Lint Code
          image: golangci/golangci-lint:v1.31.0
          script:
            #- golangci-lint run -v
            #- golangci-lint run --disable-all -E errcheck
            #- golangci-lint run --enable-all
            - echo SKIPPED
