apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-api-service
  template:
    metadata:
      labels:
        app: go-api-service
    spec:
      containers:
        - name: go-api-service
          image: aldotobing/nextapi:latest
          ports:
            - containerPort: 5000
